/**
 * File name£º RocketSim.java
 * Author£º        wangpj
 * Create Date£º 2013-12-11
 * Description:
 * 
 */

package com.sunny.simulation;

/**
 * @author wangpj
 * 
 */
public interface RocketSim {

	/**
	 * @return the mass (in kilograms) of the simulated rocket at the specified
	 *         time.
	 */
	abstract double getMass();

	/**
	 * @return the thrust force (in newtons per second) generated by the
	 *         simulated rocket.
	 */
	public double getThrust();

	/**
	 * Update the current time based on the simulation clock's.
	 * 
	 * @param t
	 *            the simulation clock's current time
	 */
	void setSimTime(double t);

}
